In [1]:
import numpy as np

X, y = np.arange(10).reshape((5, 2)), range(5)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [2]:
y

range(0, 5)

In [3]:
list(y)

[0, 1, 2, 3, 4]

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=4)

In [6]:
X_train

array([[2, 3],
       [8, 9],
       [4, 5]])

In [7]:
y_train

[1, 4, 2]

In [8]:
X_test

array([[0, 1],
       [6, 7]])

In [9]:
y_test

[0, 3]

In [10]:
train_test_split(y, shuffle=False)

[[0, 1, 2], [3, 4]]

In [11]:
from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data
y = iris.target

In [12]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [15]:
print(X_train.shape)
print(X_test.shape)

(112, 4)
(38, 4)


In [16]:
print(y_train.shape)
print(y_test.shape)

(112,)
(38,)


In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=4)

In [18]:
print(X_test.shape)
print(y_test.shape)

(60, 4)
(60,)


In [19]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [20]:
y_pred = knn.predict(X_test)

from sklearn import metrics

print(metrics.accuracy_score(y_test, y_pred))

0.9666666666666667


In [21]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(metrics.accuracy_score(y_test, y_pred))

0.9666666666666667
