In [2]:
from sklearn.datasets import load_iris
iris = load_iris()

X = iris.data
y = iris.target

In [3]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X, y)
knn.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
knn.predict(X)[0 :5]

array([0, 0, 0, 0, 0])

In [5]:
y_pred = knn.predict(X)

len(y_pred)

150

In [6]:
knn.score(X, y)

0.9666666666666667

In [7]:
from sklearn.metrics import accuracy_score
import numpy as np

y_true = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2])
y_pred1 = np.array([0, 0, 0, 1, 1, 1, 2, 2, 2, 0])
accuracy_score(y_true, y_pred1)

0.9

In [8]:
from sklearn import metrics

print(metrics.accuracy_score(y, y_pred))

0.9666666666666667


In [9]:
import numpy as np

np.mean(y_pred == y)

0.9666666666666667

In [10]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X, y)
y_pred = knn.predict(X)
print(metrics.accuracy_score(y, y_pred))

1.0


In [11]:
#import confusion_matrix
from sklearn.metrics import confusion_matrix

confusion_matrix(y,y_pred)

array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0,  0, 50]], dtype=int64)